spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:localhost://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    hiddenmethod:
      filter:
        enabled: true